/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // Material Design 3 colors — aligned with IronGrid palette
      colors: {
        surface: '#0a151a',
        'surface-dim': '#0a151a',
        'surface-bright': '#2b363d',
        'surface-container-lowest': '#051015',
        'surface-container-low': '#121d23',
        'surface-container': '#162127',
        'surface-container-high': '#202b32',
        'surface-container-highest': '#2b363d',
        'surface-variant': '#2b363d',
        primary: '#9ecaff',
        'primary-container': '#001b34',
        'on-primary': '#003258',
        'on-primary-container': '#0087df',
        'primary-fixed': '#cfe4ff',
        'primary-fixed-dim': '#9ecaff',
        'on-primary-fixed': '#001c37',
        'on-primary-fixed-variant': '#004882',
        secondary: '#b4cad6',
        'secondary-container': '#374c56',
        'on-secondary': '#1e333d',
        'on-secondary-container': '#cfe5f1',
        'secondary-fixed': '#d0e6f2',
        'secondary-fixed-dim': '#b4cad6',
        'on-secondary-fixed': '#071e27',
        'on-secondary-fixed-variant': '#374c56',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        tertiary: '#ffb5a0',
        'tertiary-container': '#380900',
        'on-tertiary': '#5f1500',
        'on-tertiary-container': '#ffdbd0',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb5a0',
        'on-tertiary-fixed': '#3a0900',
        'on-tertiary-fixed-variant': '#5f1500',
        background: '#0a151a',
        'on-background': '#d8e4ec',
        'on-surface': '#d8e4ec',
        'on-surface-variant': '#c4c6cc',
        outline: '#8e9099',
        'outline-variant': '#44474c',
        'inverse-surface': '#d8e4ec',
        'inverse-primary': '#0060a9',
        'surface-tint': '#9ecaff',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
